using Reqnroll;
using System;
using System.Collections.Generic;
using System.Text;

namespace SFA.DAS.LearnerNotifications.Tests.Acceptance.StepDefinitions
{
    [Binding]
    public class LearnerNotificationsStepDefinitions
    {
        private readonly ScenarioContext scenarioContext;
        private readonly TestingContext testingContext;

        public LearnerNotificationsStepDefinitions(ScenarioContext scenarioContext, TestingContext testingContext)
        {
            this.scenarioContext = scenarioContext;
            this.testingContext = testingContext;
        }

        [Given("a learner notification has been generated by a client application")]
        public void GivenALearnerNotificationHasBeenGeneratedByAClientApplication()
        {
        }

        [When("the learner notifications background service processes the notification")]
        public void WhenTheLearnerNotificationsBackgroundServiceProcessesTheNotification()
        {
            throw new PendingStepException();
        }

        [Then("the notification should be stored in the database")]
        public void ThenTheNotificationShouldBeStoredInTheDatabase()
        {
            throw new PendingStepException();
        }

    }
}
