using Reqnroll;
using SFA.DAS.LearnerNotifications.Messages.Commands;
using System;
using System.Collections.Generic;
using System.Text;

namespace SFA.DAS.LearnerNotifications.Tests.Acceptance.StepDefinitions
{
    [Binding]
    public class LearnerNotificationsStepDefinitions
    {
        private readonly ScenarioContext scenarioContext;
        private readonly TestingContext testingContext;
        private LearnerNotification learnerNotification; 

        public LearnerNotificationsStepDefinitions(ScenarioContext scenarioContext, TestingContext testingContext)
        {
            this.scenarioContext = scenarioContext;
            this.testingContext = testingContext;
        }

        [Given("a learner notification has been generated by a client application")]
        public void GivenALearnerNotificationHasBeenGeneratedByAClientApplication()
        {
            learnerNotification = new SFA.DAS.LearnerNotifications.Messages.Commands.LearnerNotification
            {
                CorrelationId = Guid.NewGuid(),
                LearnerAccountId = Guid.NewGuid(),
                Category = "TestCategory",
                Heading = "Test Heading",
                Body = "Test Body",
                LinkUrl = "http://test.com",
                NotificationTime = DateTime.UtcNow,
                TimeToExpire = DateTime.UtcNow.AddDays(7)
            };
        }

        [When("the learner notifications background service processes the notification")]
        public async Task WhenTheLearnerNotificationsBackgroundServiceProcessesTheNotification()
        {
            await testingContext.Send(learnerNotification);
        }

        [Then("the notification should be stored in the database")]
        public void ThenTheNotificationShouldBeStoredInTheDatabase()
        {
            throw new PendingStepException();
        }

    }
}
