using NUnit.Framework;
using Reqnroll;
using SFA.DAS.LearnerNotifications.Messages.Commands;
using SFA.DAS.LearnerNotifications.Models;
using System;
using System.Collections.Generic;
using System.Text;

namespace SFA.DAS.LearnerNotifications.Tests.Acceptance.StepDefinitions
{
    [Binding]
    public class LearnerNotificationsStepDefinitions
    {
        private readonly ScenarioContext scenarioContext;
        private readonly TestingContext testingContext;
        private LearnerNotification learnerNotification;
        private Models.Notification storedNotification;

        public LearnerNotificationsStepDefinitions(ScenarioContext scenarioContext, TestingContext testingContext)
        {
            this.scenarioContext = scenarioContext;
            this.testingContext = testingContext;
        }

        [Given("a learner notification has been generated by a client application")]
        public void GivenALearnerNotificationHasBeenGeneratedByAClientApplication()
        {
            learnerNotification = new SFA.DAS.LearnerNotifications.Messages.Commands.LearnerNotification
            {
                CorrelationId = Guid.NewGuid(),
                LearnerAccountId = Guid.NewGuid(),
                Category = "TestCategory",
                Heading = "Test Heading",
                Body = "Test Body",
                LinkUrl = "http://test.com",
                NotificationTime = DateTime.UtcNow,
                TimeToExpire = DateTime.UtcNow.AddDays(7)
            };
        }

        [When("the learner notifications background service processes the notification")]
        public async Task WhenTheLearnerNotificationsBackgroundServiceProcessesTheNotification()
        {
            await testingContext.Send(learnerNotification);
        }

        [Then("the notification should be stored")]
        public async Task ThenTheNotificationShouldBeStoredInTheDatabase()
        {
            await testingContext.WaitForIt(() =>
            {
                storedNotification = testingContext.DataContext.Notifications.FirstOrDefault(notification => notification.CorrelationId == learnerNotification.CorrelationId);
                return storedNotification != null;
            }, "Failed to find the notification in the database");
            //got the notification, now check the details are correct
            Assert.AreEqual(learnerNotification.Heading, storedNotification.Heading, "Heading does not match.");
            Assert.AreEqual(learnerNotification.Body, storedNotification.Body, "Body does not match.");
            Assert.AreEqual(learnerNotification.LinkUrl, storedNotification.LinkUrl, "LinkUrl does not match.");
            Assert.AreEqual(learnerNotification.Category, storedNotification.Category, "Category does not match.");
            Assert.AreSame(learnerNotification.LearnerAccountId, storedNotification.LearnerAccountId, "LearnerAccountId does not match.");
        }

        [Then("the notification should have a status of {string}")]
        public void ThenTheNotificationShouldHaveAStatusOf(string statusDescription)
        {
            Assert.IsTrue(Enum.TryParse< NotificationStatus>(statusDescription, out NotificationStatus status),$"Failed to parse notification status. Status from step: {statusDescription}"); 
            Assert.AreEqual(status, storedNotification.Status, $"Expected notification status to be {status} but the stored was {storedNotification.Status}");

        }
    }
}
