Feature: Receive And Store Learner Notifications

As a learner
I need the Learner Notifications Background Service to store my notifications
So that they are available in the future


Scenario: Receives a notification and stores it in the database
	Given a learner notification has been generated by a client application
	When the learner notifications background service processes the notification
	Then the notification should be stored in the database
