Feature: Receive And Store Learner Notifications

As a learner
I need the Learner Notifications Background Service to store my notifications
So that I can view them within the Apprentice facing applications


Scenario: Receives a notification and stores it so that a learner can view it in the future
	Given a learner notification has been generated by a client application
	When the learner notifications background service processes the notification
	Then the notification should be stored

Scenario: New notifications are stored with a default status of "Unread"
	Given a learner notification has been generated by a client application
	When the learner notifications background service processes the notification
	Then the notification should be stored
	And the notification should have a status of "Unread"
