<Project Sdk="Azure.Functions.Sdk/0.4.0">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<FunctionsWriteMetadataJson>true</FunctionsWriteMetadataJson>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.52.0" />
	<!--<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.0.7" OutputItemType="Analyzer" PrivateAssets="all" />-->
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.2.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Timer" Version="4.3.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.22.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
	<PackageReference Include="Microsoft.Data.SqlClient.Extensions.Azure" Version="1.0.0" />
    <PackageReference Include="SFA.DAS.Configuration.AzureTableStorage" Version="3.0.84" />
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SFA.DAS.LearnerNotifications.Application\SFA.DAS.LearnerNotifications.Application.csproj" />
    <ProjectReference Include="..\SFA.DAS.LearnerNotifications.Data\SFA.DAS.LearnerNotifications.Data.csproj" />
    <ProjectReference Include="..\SFA.DAS.LearnerNotifications.Domain\SFA.DAS.LearnerNotifications.Domain.csproj" />
    <ProjectReference Include="..\SFA.DAS.LearnerNotifications.Messages\SFA.DAS.LearnerNotifications.Messages.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>