<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
        <PackageReference Include="Azure.Identity" Version="1.17.1" />
		<PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.1" />
        <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
        <PackageReference Include="Microsoft.Azure.Services.AppAuthentication" Version="1.6.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.8" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.8" />
        <PackageReference Include="Microsoft.Identity.Client" Version="4.80.0" />
        <PackageReference Include="Polly" Version="8.5.0" />


        <PackageReference Include="MediatR" Version="12.4.1" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SFA.DAS.LearnerNotifications.Messages\SFA.DAS.LearnerNotifications.Messages.csproj" />
		<ProjectReference Include="..\SFA.DAS.LearnerNotifications.Models\SFA.DAS.LearnerNotifications.Models.csproj" />
        <ProjectReference Include="..\SFA.DAS.LearnerNotifications.Domain\SFA.DAS.LearnerNotifications.Domain.csproj" />
        <ProjectReference Include="..\SFA.DAS.LearnerNotifications.Data\SFA.DAS.LearnerNotifications.Data.csproj" />
	</ItemGroup>

</Project>
