CREATE TABLE [dbo].[Status](
    [Id] [tinyint] NOT NULL,
    [Description] [nvarchar](255) NOT NULL
) ON [PRIMARY];
GO

ALTER TABLE [dbo].[Status] ADD PRIMARY KEY CLUSTERED 
(
    [Id] ASC
) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
GO