<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Bogus" Version="35.6.5" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.8" />
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.8" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.8" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
		<PackageReference Include="NServiceBus" Version="10.2.3" />
		<PackageReference Include="NServiceBus.Transport.AzureServiceBus" Version="6.3.0" />
		<PackageReference Include="NUnit" Version="3.14.0" />
		<PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
		<PackageReference Include="Reqnroll.Microsoft.Extensions.DependencyInjection" Version="3.3.4" />
		<PackageReference Include="Reqnroll.NUnit" Version="3.3.4" />
		<PackageReference Include="NUnit.ConsoleRunner" Version="3.22.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\SFA.DAS.LearnerNotifications.Messages\SFA.DAS.LearnerNotifications.Messages.csproj" />
	  <ProjectReference Include="..\SFA.DAS.LearnerNotifications.Models\SFA.DAS.LearnerNotifications.Models.csproj" />
	</ItemGroup>


	<ItemGroup>
		<None Update="appSettings.development.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="appSettings.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>